import type { Metadata } from "next";
import { Cairo } from "next/font/google"; // Import Cairo from Google Fonts
import "./globals.css";

const cairo = Cairo({
  subsets: ["latin"],
  weight: "600", 
});

export const metadata: Metadata = {
  title: "memory flash game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased bg-dbg`}>
        {children}
      </body>
    </html>
  );
}
