name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or the version you prefer

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - name: Build the app
      run: pnpm run build

    - name: Export static files
      run: pnpm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # Change this if your output directory is different
